export const WITHDRAW_POP_UP_CHANGE = 'WITHDRAW_POP_UP_CHANGE';

export const WARNING_POP_UP_CHANGE = 'WARNING_POP_UP_CHANGE';

export const ASSETS_POP_UP_CHANGE = 'ASSETS_POP_UP_CHANGE';

export const PROFILE_MENU_CHANGE = 'PROFILE_MENU_CHANGE';

export const PROFILE_EDIT_CHANGE = 'PROFILE_EDIT_CHANGE';

export const TRANSACTION_HISTORY_CHANGE = 'TRANSACTION_HISTORY_CHANGE';

export const SET_NETWORK = 'SET_NETWORK';

export const SET_TOKEN = 'SET_TOKEN';
